apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: photos-pvc
  namespace: dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: random-photos-api
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: random-photos-api
  template:
    metadata:
      labels:
        app: random-photos-api
    spec:
      containers:
        - name: random-photos-api
          image: random-photos-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: photos-volume
              mountPath: /photos
      volumes:
        - name: photos-volume
          persistentVolumeClaim:
            claimName: photos-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: random-photos-api
  namespace: dev
spec:
  selector:
    app: random-photos-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: random-photos-api-ingress
  namespace: dev
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: photos.local
      http:
        paths:
          - path: /api/images
            pathType: ImplementationSpecific
            backend:
              service:
                name: random-photos-api
                port:
                  number: 80